# src/latest_ai_development/config/tasks.yaml
retrieve_document_chunks:
  description: >
      Use the document_retrieval_tool to find and return relevant document chunks for the user query: "{query}".
      Simply pass the user query to the document_retrieval_tool and return the formatted chunks as provided by the tool.
      The tool already handles formatting and returns the chunks in the appropriate structure.
  expected_output: >
      Return the formatted document chunks exactly as provided by the document_retrieval_tool.
      The tool handles all formatting and metadata inclusion.
      if no relevant documents are found, return an empty list.
  agent: document_researcher

answer_task:
  description: >
    Analyze the provided document context and formulate a comprehensive and accurate answer to the user's original question: {query}.
  expected_output: >
    A professional, well-structured response that directly answers the user's question. Format the response naturally and appropriately based on the content:

    Guidelines for response formatting:
    - Start with a clear, direct answer to the question
    - Provide supporting details, explanations, or calculations only when relevant
    - Include specific references to policy articles, sections, or documents when citing sources
    - Use natural language flow rather than rigid templates
    - Adapt the structure to fit the content (simple answers for simple questions, detailed breakdowns for complex ones)
    - Use proper formatting (bullet points, numbering, or paragraphs) as appropriate for the content
    - Ensure professional tone and clarity
    - Include precise figures, timeframes, and regulatory references where applicable

    The response should feel conversational yet authoritative, avoiding repetitive headers unless the content genuinely requires structured breakdown.
  agent: answer_synthesizer